### ISSUE TITLE
Shiny issue. Resources not loading

### ISSUE THREAD

**Issue by pssguy** [timelyportfolio/explodingboxplotR#2]
Love the package but...

```
library(shiny)
library(explodingboxplotR)
app <- shinyApp(
  ui = fluidPage(
    exploding_boxplotOutput("test", width = "100%", height = "400px")
  ),
  server = function(input, output) ({

  output$test <-  renderExploding_boxplot({
    exploding_boxplot(
      data.frame(
        rowname = rownames(InsectSprays),
        InsectSprays,
        stringsAsFactors = FALSE
      ),
      y = "count",
      group = "spray",
      color = "spray",
      label = "rowname"
    )

  })
})
)

runApp(app)
```

http://127.0.0.1:6501/exploding_boxplot-binding-0.0.1/exploding_boxplot.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://127.0.0.1:6501/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)

> sessionInfo()
> R version 3.2.2 (2015-08-14)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252 LC_NUMERIC=C  
[5] LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] explodingboxplotR_0.0.1 shiny_0.12.2.9000      

loaded via a namespace (and not attached):
 [1] htmlwidgets_0.5.2 R6_2.1.1          rsconnect_0.4.1.4 htmltools_0.3     tools_3.2.2       yaml_2.1.13       Rcpp_0.12.2  
 [8] jsonlite_0.9.19   digest_0.6.9      xtable_1.8-0      httpuv_1.3.3      mime_0.4

**Comment by timelyportfolio** [comment]
Thanks so much for using this thing.  When did you install?  I think I fixed this late Friday afternoon.

**Comment by timelyportfolio** [comment]
@pssguy, I just realized I only fixed this in the `feature/crosstalk` branch.  I'll try to fix in `master` tomorrow.   Sorry.

**Comment by pssguy** [comment]
Cheers
What would be code for installing this branch? The crosstalk would be useful bonus anyways

**Comment by timelyportfolio** [comment]
I should have pointed to this [example](https://github.com/timelyportfolio/explodingboxplotR/blob/feature/crosstalk/inst/examples/examples_crosstalk.R).  Note, I have plugged in only the `mouseover`/`mouseout` events.  I started implementing `implode` and `explode`.  Just in case you didn't know, double-click restores the boxplot.  There is an issue https://github.com/mcaule/d3_exploding_boxplot/issues/2 on the source to add a way to restore/implode on touch devices.

I forgot that for now I am not going to merge to `master` since this introduces a dependency on the experimental `crosstalk`.
